services:
  integration_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: 'goschool-app-integration-test'
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
    env_file:
      - .env.test
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - goschool_net_test
    command: sh -c "go test -v ./integration/..."

  postgres:
    image: postgres:16-alpine
    container_name: 'goschool-postgres-test'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${PG_USER} -d ${PG_DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - goschool_net_test

networks:
  goschool_net_test:
    driver: bridge
